GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJNYXVsYW5hIEFrYmFyIiwiZW1haWwiOiJtYXVsYW5hQGdtYWlsLmNvbSIsImlhdCI6MTc0OTI4NDU0MSwiZXhwIjoxNzQ5Mjg1NDQxfQ.TNoBMLWJSTM1OIXwIZAJMtUs_PbY4g7b33xrEuTzZz8

###
POST  http://localhost:5000/users
Content-Type: application/json

{
    // Step 1 - Basic Info
    "name": "Maulana Akbar",
    
    // Step 2 - Personal Info
    "country": "indonesia", 
    "gender": "male",
    "age": 25,
    
    // Step 3 - Physical Info
    "height": 170,
    "currentWeight": 75.5,
    "targetWeight": 70,
    
    // Step 4 - Goals  
    "weeklyTarget": 0.5,
    "targetDeadline": "2024-12-31",
    
    // Step 5 - Activity
    "activityLevel": 1.55,
    
    // Step 6 - Calories (optional, akan dihitung otomatis)
    // "targetCalories": 2000,
    
    // Step 7 - Account
    "username": "maulana12345",
    "email": "maulana123@gmail.com", 
    "password": "123456789",
    "confirmPassword": "123456789"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "maulana@gmail.com",
    "password": "12345678"
}

###
GET http://localhost:5000/token

###
DELETE  http://localhost:5000/logout